CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(15) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(255) NULL,
    user_type INT NOT NULL DEFAULT 1,
    is_otp_verified TINYINT NOT NULL DEFAULT 0,
    gov_id_type ENUM('aadhar', 'gst') DEFAULT NULL,
    gov_id_val TINYINT DEFAULT NULL,
    is_gov_id_verified TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
